### ISSUE TITLE
line 479 __verbose improvement if use set -Eeou pipefail inside release.sh script

### ISSUE THREAD

**Issue by ghost** [pnikosis/semtag#2]
If you use inside release.sh script: set -Eeou pipefail  
* semtag line:479  => local __verbose=${2:-''}

By the way the release.sh could be changed to work outside the source code and and .gitignore "semtag*" or similar. Improvement would be rewrite to script to change version in all files recursive in an given release folder - but its questionary to change always the source code to add the version number.

**Comment by nico2sh** [comment]
to be honest, I kind of hate the release.sh script, as it actually changes the code of the executable file, happy to get PRs though
