### ISSUE TITLE
Feature Request: Multiple remotes

### ISSUE THREAD

**Issue by damianoneill** [pnikosis/semtag#3]
Hi Nico, first thanks for the tool, very useful.  

Could you consider adding support for the use case where multiple remotes are defined.  I imagine lots of developers will follow a origin / fork strategy.  At the moment, the remote check 'git remote' can return a list, which will fail in the following git push.

It would be useful to support pushing to one or more remotes.  

Thanks,
Damian.

**Comment by damianoneill** [comment]
@pnikosis wonder if you had a chance to consider this?  Noted that @asveepay had raised a PR for this.  https://github.com/pnikosis/semtag/pull/1

**Comment by nico2sh** [comment]
Merged! Thanks
