### ISSUE TITLE
tag version > 10

### ISSUE THREAD

**Issue by damianoneill** [pnikosis/semtag#4]
I have a tag that semtag has just moved to v19.1.1-beta.10.  This is generated with 

```sh
source semtag beta
```

I have since done a few commits, when I run the semtag command it wont move passed 10.  Have you previously seen an example > 10?  

Thanks,
Damian.

**Comment by nico2sh** [comment]
I've gone beyond 10, weird... I'll check it out, thanks Damian.

**Comment by chaosblog** [comment]
Something very similar here. My last tag, created with semtag, is: v0.1.0-rc.10.

With `semtag getcurrent` I get _v0.1.0-rc.9.1+c6cc6f5_

When I try adding a newer rc via `semtag candidate -s minor` semtag tries to create v0.1.0-rc.10 again which results in an error.
After another commit I added rc.11 tag manually and `semtag getcurrent` gives me v_0.1.0-rc.9.2+1d5515d_ then.

**Comment by soupdiver** [comment]
Similiar issue here. Instead `v0.6.0-alpha.10` I get `v0.6.0-alpha.a`.
Tag was created manually but parsed by `semtag`. Since `a` is hex for `10` I guess it's a formatting problem somewhere 🤔

**Comment by chaosblog** [comment]
I tested the version from #13 and it fixes the problem. Please merge the pull request. Thanks.

**Comment by nico2sh** [comment]
Merged and fixed
