### ISSUE TITLE
How to maintain several major releases?

### ISSUE THREAD

**Issue by antonbabenko** [pnikosis/semtag#9]
I have to maintain two different versions - `v2.*` and `v1.*` (for legacy and bug-fixes).

Now I got "Version can't be lower than last version: v2.0.0" if I try to release into v1:

```
semtag final -v v1.23.0 -f
```

Any ideas? Or workarounds?

**Comment by nico2sh** [comment]
nope, sadly the versions can only be incremental, only workaround comes to my mind is to maintain a fork of your code with its own versioning each
